### ISSUE TITLE
Microsoft OpenID authorization URL acquisition does not expect proper URLs

### ISSUE THREAD

**Issue by JibbityJobbity** [panva/oauth4webapi#100]
### What happened?

When using with auth/core 0.18.6 and with the Azure AD , I get this error showing up:

```
[auth][error] OperationProcessingError: "response" body "issuer" does not match "expectedIssuer"
logger.js:9
    at Module.processDiscoveryResponse (file:///path/to/project/node_modules/.pnpm/oauth4webapi@2.6.0/node_modules/oauth4webapi/build/index.js:252:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAuthorizationUrl (file:///path/to/project/node_modules/.pnpm/@auth+core@0.18.6/node_modules/@auth/core/lib/actions/signin/authorization-url.js:19:20)
    at async Module.signIn (file:///path/to/project/node_modules/.pnpm/@auth+core@0.18.6/node_modules/@auth/core/lib/actions/signin/index.js:10:56)
    at async AuthInternal (file:///path/to/project/node_modules/.pnpm/@auth+core@0.18.6/node_modules/@auth/core/lib/index.js:58:24)
    at async Proxy.Auth (file:///path/to/project/node_modules/.pnpm/@auth+core@0.18.6/node_modules/@auth/core/index.js:104:29)
    at async Module.respond (/path/to/project/node_modules/.pnpm/@sveltejs+kit@1.30.3_svelte@3.59.2_vite@4.5.1/node_modules/@sveltejs/kit/src/runtime/server/respond.js:282:20)
    at async file:///path/to/project/node_modules/.pnpm/@sveltejs+kit@1.30.3_svelte@3.59.2_vite@4.5.1/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:510:22
```

It gets the authentication URL from the correct place: `'https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration'`, but when we process the result, we end up in this error.

In this check:
- `expectedIssuerIdentifier.href` 'https://login.microsoftonline.com/common/v2.0'
- `json.issuer` 'https://login.microsoftonline.com/{tenantid}/v2.0' (they quite literally provide you with `{tenantid}` in that response url)

I used these hacks and it seems to work from what I can tell:

```
processDiscoveryResponse near the bottom:
    // if (new URL(json.issuer).href !== expectedIssuerIdentifier.href) {
    //     throw new OPE('"response" body "issuer" does not match "expectedIssuer"');
    // }
    json.issuer = expectedIssuerIdentifier.href;
    return json;

for some reason, validateIssuer gets supplied with a URL from some weird tenant ID and
it's freaking out because it isn't common. replace with:

function validateIssuer(expected, result) {
    // if (result.claims.iss !== expected) {
    //     throw new OPE('unexpected JWT "iss" (issuer) claim value');
    // }
    return result;
}
```

Let me know if this is an auth js core issue, but the nature in which azure expects tenant IDs to be replaced by the server/client makes this issue out to be like it's in this library's domain.

### Version

2.6.0

### Runtime

Node.js

### Runtime Details

cba, honestly don't think it matters

### Code to reproduce

```js
/* this is just copy pasted from auth js core */
import * as checks from "../callback/oauth/checks.js";
import * as o from "oauth4webapi";
/**
 * Generates an authorization/request token URL.
 *
 * [OAuth 2](https://www.oauth.com/oauth2-servers/authorization/the-authorization-request/)
 */
export async function getAuthorizationUrl(query, options) {
    const { logger, provider } = options;
    let url = provider.authorization?.url;
    let as;
    // Falls back to authjs.dev if the user only passed params
    if (!url || url.host === "authjs.dev") {
        // If url is undefined, we assume that issuer is always defined
        // We check this in assert.ts
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        const issuer = new URL(provider.issuer);
        const discoveryResponse = await o.discoveryRequest(issuer);
        const as = await o.processDiscoveryResponse(issuer, discoveryResponse); // HERE IS THE CAUSE OF THE ISSUE
        if (!as.authorization_endpoint) {
            throw new TypeError("Authorization server did not provide an authorization endpoint.");
        }
        url = new URL(as.authorization_endpoint);
    }
    const authParams = url.searchParams;
    let redirect_uri = provider.callbackUrl;
    let data;
    if (!options.isOnRedirectProxy && provider.redirectProxyUrl) {
        redirect_uri = provider.redirectProxyUrl;
        data = { origin: provider.callbackUrl };
        logger.debug("using redirect proxy", { redirect_uri, data });
    }
    const params = Object.assign({
        response_type: "code",
        // clientId can technically be undefined, should we check this in assert.ts or rely on the Authorization Server to do it?
        client_id: provider.clientId,
        redirect_uri,
        // @ts-expect-error TODO:
        ...provider.authorization?.params,
    }, Object.fromEntries(provider.authorization?.url.searchParams ?? []), query);
    for (const k in params)
        authParams.set(k, params[k]);
    const cookies = [];
    const state = await checks.state.create(options, data);
    if (state) {
        authParams.set("state", state.value);
        cookies.push(state.cookie);
    }
    if (provider.checks?.includes("pkce")) {
        if (as && !as.code_challenge_methods_supported?.includes("S256")) {
            // We assume S256 PKCE support, if the server does not advertise that,
            // a random `nonce` must be used for CSRF protection.
            if (provider.type === "oidc")
                provider.checks = ["nonce"];
        }
        else {
            const { value, cookie } = await checks.pkce.create(options);
            authParams.set("code_challenge", value);
            authParams.set("code_challenge_method", "S256");
            cookies.push(cookie);
        }
    }
    const nonce = await checks.nonce.create(options);
    if (nonce) {
        authParams.set("nonce", nonce.value);
        cookies.push(nonce.cookie);
    }
    // TODO: This does not work in normalizeOAuth because authorization endpoint can come from discovery
    // Need to make normalizeOAuth async
    if (provider.type === "oidc" && !url.searchParams.has("scope")) {
        url.searchParams.set("scope", "openid profile email");
    }
    logger.debug("authorization url is ready", { url, cookies, provider });
    return { redirect: url.toString(), cookies };
}
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/oauth4webapi/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Azure's common interfaces are an unfortunate design that is in direct contradiction of the specifications it implements.

It is unfortunate they force their customers through extra hoops if they wish to not use their own proprietary SDKs.

Using Azure's own SDKs would be my general recommendation, but I understand that's not an option when using frameworks such as next-auth.

To that end, if next-auth wishes to suppport the common endpoints of Azure AD they need to work around Azure's non-conform behaviours, e.g. like so


```js
import * as oauth from './build/index.js'
import * as jose from 'jose'

const as = await oauth
  .discoveryRequest(new URL('https://login.microsoftonline.com/common/v2.0'))
  .then((response) =>
    oauth.processDiscoveryResponse(
      new URL('https://login.microsoftonline.com/{tenantid}/v2.0'),
      response,
    ),
  )

let tenantId
const response = oauth.authorizationCodeGrantRequest(
  as,
  client,
  params,
  redirectUri,
  codeVerifier,
  {
    [oauth.experimental_customFetch]: (input, init) =>
      fetch(input, init).then(async (res) => {
        if (res.status === 200) {
          const { id_token } = await res.clone().json()
          ;({ tid: tenantId } = jose.decodeJwt(id_token))
        }

        return res
      }),
  },
)

if (!isThisTenantIdExpected(tenantId)) {
  throw new Error()
}

const result = await oauth.processAuthorizationCodeOAuth2Response(
  {
    ...as,
    issuer: as.issuer.replace('{tenantid}', tenantId),
  },
  client,
  response,
)
```

**Comment by JibbityJobbity** [comment]
Getting next-auth to play along with Microsoft's silly special case is going to be interesting...
Ah well, thanks for checking it out. The snippet is helpful.

**Comment by panva** [comment]
It shouldn't be a big deal. Cc @balazsorban44

**Comment by panva** [comment]
FYI https://github.com/panva/oauth4webapi/pull/131#issuecomment-2351806266
